title: Tobias Riedlinger
logo: assets/images/mugshot2.png
# description: Postdoctoral researcher in mathematics at TU Berlin
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
